# -*- coding: utf-8 -*-
"""Untitled40.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13D8fqFUgO_aP3IJWnbH-Xh4-YPaivS3w
"""

pip install streamlit

import streamlit as st

st.title('IPL Win Predictor')

